# Add 'service' label to any change to microservice files within the source dir
service/aslan:
- pkg/microservice/aslan/**/*.go

service/cron:
- pkg/microservice/cron/**/*.go

service/podexec:
- pkg/microservice/podexec/**/*.go

service/predator:
- pkg/microservice/predator/**/*.go

service/reaper:
- pkg/microservice/reaper/**/*.go

service/warpdrive:
- pkg/microservice/warpdrive/**/*.go

service/hubserver:
- pkg/microservice/hubserver/**/*.go
