// /*
// * Copyright 2023 The KodeRover Authors.
// *
// * Licensed under the Apache License, Version 2.0 (the "License");
// * you may not use this file except in compliance with the License.
// * You may obtain a copy of the License at
// *
// *     http://www.apache.org/licenses/LICENSE-2.0
// *
// * Unless required by applicable law or agreed to in writing, software
// * distributed under the License is distributed on an "AS IS" BASIS,
// * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// * See the License for the specific language governing permissions and
// * limitations under the License.
// */
package dingtalk

type ApprovalDefinition struct {
}

//type AutoGenerated struct {
//	Name           string           `json:"name"`
//	Description    string           `json:"description"`
//	FormComponents []FormComponents `json:"formComponents"`
//}
//type Props struct {
//	Label       string `json:"label"`
//	Placeholder string `json:"placeholder"`
//	ComponentID string `json:"componentId"`
//	Required    bool   `json:"required"`
//	BizAlias    string `json:"bizAlias"`
//}
//type Props0 struct {
//	Label       string `json:"label"`
//	Placeholder string `json:"placeholder"`
//	ComponentID string `json:"componentId"`
//	Required    bool   `json:"required"`
//}
//type Props1 struct {
//	Label        string `json:"label"`
//	Placeholder  string `json:"placeholder"`
//	ComponentID  string `json:"componentId"`
//	Required     bool   `json:"required"`
//	Unit         string `json:"unit"`
//	DefaultValue string `json:"defaultValue"`
//}
//type Options struct {
//	Value string `json:"value"`
//	Key   string `json:"key"`
//}
//type Props2 struct {
//	Options     []Options `json:"options"`
//	Label       string    `json:"label"`
//	Placeholder string    `json:"placeholder"`
//	ComponentID string    `json:"componentId"`
//	Required    bool      `json:"required"`
//}
//type Props3 struct {
//	Options     []Options `json:"options"`
//	Label       string    `json:"label"`
//	Placeholder string    `json:"placeholder"`
//	ComponentID string    `json:"componentId"`
//	Required    bool      `json:"required"`
//}
//type Props4 struct {
//	Unit         string `json:"unit"`
//	Format       string `json:"format"`
//	BizAlias     string `json:"bizAlias"`
//	Label        string `json:"label"`
//	Placeholder  string `json:"placeholder"`
//	ComponentID  string `json:"componentId"`
//	Required     bool   `json:"required"`
//	DefaultValue string `json:"defaultValue"`
//}
//type Props5 struct {
//	Unit          string `json:"unit"`
//	Format        string `json:"format"`
//	BizAlias      string `json:"bizAlias"`
//	Label         string `json:"label"`
//	Placeholder   string `json:"placeholder"`
//	ComponentID   string `json:"componentId"`
//	Duration      bool   `json:"duration"`
//	DurationLabel string `json:"durationLabel"`
//	Required      bool   `json:"required"`
//}
//type Props6 struct {
//	Link        string `json:"link"`
//	NotPrint    string `json:"notPrint"`
//	BizAlias    string `json:"bizAlias"`
//	ComponentID string `json:"componentId"`
//	Content     string `json:"content"`
//}
//type Props7 struct {
//	Mode        string `json:"mode"`
//	Label       string `json:"label"`
//	Placeholder string `json:"placeholder"`
//	ComponentID string `json:"componentId"`
//	Required    bool   `json:"required"`
//}
//type Props8 struct {
//	Label       string `json:"label"`
//	ComponentID string `json:"componentId"`
//	Required    bool   `json:"required"`
//}
//type Props9 struct {
//	Upper       string `json:"upper"`
//	Label       string `json:"label"`
//	Placeholder string `json:"placeholder"`
//	ComponentID string `json:"componentId"`
//	Required    bool   `json:"required"`
//}
//type Props struct {
//	Label       string `json:"label"`
//	Placeholder string `json:"placeholder"`
//	ComponentID string `json:"componentId"`
//	Required    bool   `json:"required"`
//}
//type Props0 struct {
//	PayEnable   bool   `json:"payEnable"`
//	Upper       string `json:"upper"`
//	BizAlias    string `json:"bizAlias"`
//	Label       string `json:"label"`
//	Placeholder string `json:"placeholder"`
//	ComponentID string `json:"componentId"`
//	Required    bool   `json:"required"`
//}
//type Props1 struct {
//	Unit        string `json:"unit"`
//	PayEnable   bool   `json:"payEnable"`
//	BizAlias    string `json:"bizAlias"`
//	Label       string `json:"label"`
//	Placeholder string `json:"placeholder"`
//	ComponentID string `json:"componentId"`
//	Required    bool   `json:"required"`
//}
//type Children struct {
//	ComponentType string `json:"componentType"`
//	Props         Props  `json:"props,omitempty"`
//	Props0        Props0 `json:"props,omitempty"`
//	Props1        Props1 `json:"props,omitempty"`
//}
//type StatField struct {
//	Upper       string `json:"upper,omitempty"`
//	ComponentID string `json:"componentId"`
//	Label       string `json:"label"`
//}
//type Props10 struct {
//	TableViewMode string      `json:"tableViewMode"`
//	VerticalPrint bool        `json:"verticalPrint"`
//	StatField     []StatField `json:"statField"`
//	BizAlias      string      `json:"bizAlias"`
//	Label         string      `json:"label"`
//	ComponentID   string      `json:"componentId"`
//}
//type Props11 struct {
//	Label       string `json:"label"`
//	ComponentID string `json:"componentId"`
//	Required    bool   `json:"required"`
//}
//type Props12 struct {
//	Label       string `json:"label"`
//	Placeholder string `json:"placeholder"`
//	ComponentID string `json:"componentId"`
//	Choice      string `json:"choice"`
//	Required    bool   `json:"required"`
//	BizAlias    string `json:"bizAlias"`
//}
//type Props13 struct {
//	Multiple    bool   `json:"multiple"`
//	Label       string `json:"label"`
//	Placeholder string `json:"placeholder"`
//	ComponentID string `json:"componentId"`
//	Required    bool   `json:"required"`
//}
//type AvailableTemplates struct {
//	Name        string `json:"name"`
//	ProcessCode string `json:"processCode"`
//}
//type Props14 struct {
//	Label              string               `json:"label"`
//	Placeholder        string               `json:"placeholder"`
//	ComponentID        string               `json:"componentId"`
//	Required           bool                 `json:"required"`
//	BizAlias           string               `json:"bizAlias"`
//	AvailableTemplates []AvailableTemplates `json:"availableTemplates"`
//}
//type Props15 struct {
//	AddressModel string `json:"addressModel"`
//	BizAlias     string `json:"bizAlias"`
//	Label        string `json:"label"`
//	ComponentID  string `json:"componentId"`
//	Required     bool   `json:"required"`
//}
//type Props16 struct {
//	Limit       int    `json:"limit"`
//	Label       string `json:"label"`
//	Placeholder string `json:"placeholder"`
//	ComponentID string `json:"componentId"`
//	Required    bool   `json:"required"`
//	BizAlias    string `json:"bizAlias"`
//}
//type FormComponents struct {
//	ComponentType string     `json:"componentType"`
//	Props         Props      `json:"props,omitempty"`
//	Props0        Props0     `json:"props,omitempty"`
//	Props1        Props1     `json:"props,omitempty"`
//	Props2        Props2     `json:"props,omitempty"`
//	Props3        Props3     `json:"props,omitempty"`
//	Props4        Props4     `json:"props,omitempty"`
//	Props5        Props5     `json:"props,omitempty"`
//	Props6        Props6     `json:"props,omitempty"`
//	Props7        Props7     `json:"props,omitempty"`
//	Props8        Props8     `json:"props,omitempty"`
//	Props9        Props9     `json:"props,omitempty"`
//	Children      []Children `json:"children,omitempty"`
//	Props10       Props10    `json:"props,omitempty"`
//	Props11       Props11    `json:"props,omitempty"`
//	Props12       Props12    `json:"props,omitempty"`
//	Props13       Props13    `json:"props,omitempty"`
//	Props14       Props14    `json:"props,omitempty"`
//	Props15       Props15    `json:"props,omitempty"`
//	Props16       Props16    `json:"props,omitempty"`
//}

func (c *Client) CreateApproval() {

}
