apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: frontend
    app: gateway
  name: gateway
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort 
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 4000
    # comment or delete the following line if you want to use a LoadBalancer
    nodePort: 30080
  selector:
    project: piggymetrics
    tier: frontend
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    project: piggymetrics
    tier: frontend
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
     project: piggymetrics
     tier: frontend
     app: gateway  
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        project: piggymetrics
        tier: frontend
        app: gateway
    spec:
      initContainers:
        - name: init-skywalking-vm
          image: koderover.tencentcloudcr.com/koderover-demo/skywalking-vm:8.8.0
          command:
            - 'sh'
            - '-c'
            - 'set -ex;mkdir -p /vmskywalking/vm;cp -r /usr/skywalking/vm/* /vmskywalking/vm;'
          volumeMounts:
            - mountPath: /vmskywalking/vm
              name: skywalking-vm
      containers:
      - name: gateway
        env:
        - name: JAVA_OPTS
          value: "-javaagent:/opt/skywalking/vm/skywalking-vm.jar -Duser.timezone=GMT+8"
        - name: SW_AGENT_NAME
          value: "gateway"
        - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
          value: "skywalking-oap.skywalking.svc.cluster.local:11800"
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        envFrom:
        - configMapRef:
           name: special-config-env
        image: koderover.tencentcloudcr.com/koderover-demo/piggymetrics-gateway:v0.3.0
        name: gateway
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 500m
            memory: 512M
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        volumeMounts:
          - mountPath: /opt/skywalking/vm
            name: skywalking-vm
      restartPolicy: Always
      volumes:
        - name: skywalking-vm
          emptyDir: {}
