fullnameOverride: service
replicaCount: 1
port: 20221

imagePullSecretsName: "service-registry-secret"

image:
  repository: "ccr.ccs.tencentyun.com/koderover-public/service"
  tag: "latest"

resources:
  requests:
    cpu: 10m
    mem: 10Mi

  limits:
    cpu: 20m
    mem: 20Mi
