apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: auth-service
  name: auth-service
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    project: piggymetrics
    tier: infrastructure
    app: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: auth-service
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
     project: piggymetrics
     tier: infrastructure
     app: auth-service
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: infrastructure
        app: auth-service
    spec:
      initContainers:
        - name: init-skywalking-agent
          image: koderover.tencentcloudcr.com/koderover-demo/skywalking-agent:8.8.0
          command:
            - 'sh'
            - '-c'
            - 'set -ex;mkdir -p /vmskywalking/agent;cp -r /usr/skywalking/agent/* /vmskywalking/agent;'
          volumeMounts:
            - mountPath: /vmskywalking/agent
              name: skywalking-agent
      containers:
      - env:
        - name: JAVA_OPTS
          value: "-javaagent:/opt/skywalking/agent/skywalking-agent.jar -Duser.timezone=GMT+8"
        - name: SW_AGENT_NAME
          value: "auth-service"
        - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
          value: "skywalking-oap.skywalking.svc.cluster.local:11800"
        - name: ACCOUNT_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: account_service_password
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        - name: MONGODB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: auth_mongodb_password
        - name: NOTIFICATION_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: notification_service_password
        - name: STATISTICS_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: statistics_service_password
        envFrom:
        - configMapRef:
           name: special-config-env              
        image: koderover.tencentcloudcr.com/koderover-demo/piggymetrics-auth-service:v0.3.0
        name: auth-service
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 500m
            memory: 512M
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        volumeMounts:
          - mountPath: /opt/skywalking/agent
            name: skywalking-agent
      restartPolicy: Always
      volumes:
        - name: skywalking-agent
          emptyDir: {}
