apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: monitoring
  name: monitoring
spec:
  type: NodePort
  ports:
  - name: http
    port: 9000
    targetPort: 8080
    nodePort: 31090
  selector:
    project: piggymetrics
    tier: infrastructure
    app: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: monitoring
  name: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
     project: piggymetrics
     tier: infrastructure
     app: monitoring
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: infrastructure
        app: monitoring
    spec:
      initContainers:
        - name: init-skywalking-agent
          image: koderover.tencentcloudcr.com/koderover-demo/skywalking-agent:8.8.0
          command:
            - 'sh'
            - '-c'
            - 'set -ex;mkdir -p /vmskywalking/agent;cp -r /usr/skywalking/agent/* /vmskywalking/agent;'
          volumeMounts:
            - mountPath: /vmskywalking/agent
              name: skywalking-agent
      containers:
      - env:
        - name: JAVA_OPTS
          value: "-javaagent:/opt/skywalking/agent/skywalking-agent.jar -Duser.timezone=GMT+8"
        - name: SW_AGENT_NAME
          value: "monitoring"
        - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
          value: "skywalking-oap.skywalking.svc.cluster.local:11800"
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        envFrom:
        - configMapRef:
           name: special-config-env                 
        image: koderover.tencentcloudcr.com/koderover-demo/piggymetrics-monitoring:v0.3.0
        name: monitoring
        resources:
          limits:
            cpu: 500m
            memory: 1G
          requests:
            cpu: 100m
            memory: 256M        
        ports:
         - containerPort: 8080
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /opt/skywalking/agent
            name: skywalking-agent
      restartPolicy: Always
      volumes:
        - name: skywalking-agent
          emptyDir: {}
